version: 2.1

jobs:
  manual-marker-deployment:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      
      # Record deployment plan
      - run:
          name: "Create deployment plan"
          command: |
            circleci run release plan \
              --environment-name=poc-environment \
              --component-name=poc-component \
              --target-version=${CIRCLE_SHA1::12}

      # Deployment stage
      - run:
          name: "Execute deployment"
          command: |
            echo "Executing actual deployment..."
            sleep 5

      # Record deployment start
      - run:
          name: "Update deployment to running"
          command: |
            circleci run release update --status=running

      # Validation stage
      - run:
          name: "Validate deployment"
          command: |
            echo "Validating deployment result..."
            sleep 3

      # Record deployment completion
      - run:
          name: "Update deployment to complete"
          command: |
            circleci run release update --status=SUCCESS
          when: on_success
      
      # Record deployment completion
      - run:
          name: "Update deployment to failed"
          command: |
            circleci run release update --status=FAILED
          when: on_fail

  cancel-deployment:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Update planned release to CANCELED
          command: |
            circleci run release update --status=CANCELED

workflows:
  manual-deploy-marker:
    jobs:
      - manual-marker-deployment
      - cancel-deployment:
          requires:
            - manual-marker-deployment:
              - canceled