version: 2.1

jobs:
  manual-marker-deployment:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      
      # Record deployment start
      - run:
          name: "Create deployment start marker"
          command: |
            circleci run release log \
              --environment-name=poc-environment \
              --component-name=poc-component \
              --target-version=v1.0.0 \
              --description="Deployment started"
      
      # Preparation stage
      - run:
          name: "Deployment preparation stage"
          command: |
            echo "Performing preparation tasks for deployment..."
            sleep 3
      
      # Record preparation completion
      - run:
          name: "Create preparation complete marker"
          command: |
            circleci run release log \
              --environment-name=poc-environment \
              --component-name=poc-component \
              --target-version=v1.0.0 \
              --description="Preparation stage complete"
      
      # Deployment stage
      - run:
          name: "Execute deployment"
          command: |
            echo "Executing actual deployment..."
            sleep 5
      
      # Record deployment completion
      - run:
          name: "Create deployment complete marker"
          command: |
            circleci run release log \
              --environment-name=poc-environment \
              --component-name=poc-component \
              --target-version=v1.0.0 \
              --description="Deployment complete"
      
      # Validation stage
      - run:
          name: "Validate deployment"
          command: |
            echo "Validating deployment result..."
            sleep 3
      
      # Final completion and validation marker
      - run:
          name: "Create final completion marker"
          command: |
            circleci run release log \
              --environment-name=poc-environment \
              --component-name=poc-component \
              --target-version=v1.0.0 \
              --description="Deployment validation complete" \
              --deploymentType="ROLLING"

workflows:
  manual-deploy-marker:
    jobs:
      - manual-marker-deployment